services:
  soccernet-app:
    build: .
    container_name: soccernet_checker
    volumes:
      - .:/app
      - ./data:/app/data  # 대용량 영상 및 특징 데이터 저장소
    env_file:  # .env 파일을 자동으로 로드합니다.
      - .env
    ports:
      - "8501:8501"
    tty: true
    stdin_open: true
    command: streamlit run gui_app.py --server.address=0.0.0.0 --server.port=8501
